---
schema: promenade/KubernetesNetwork/v1
metadata:
  schema: metadata/Document/v1
  name: kubernetes-network
  layeringDefinition:
    abstract: false
    layer: site
data:
  dns:
    cluster_domain: cluster.local
    service_ip: 10.96.0.10
    bootstrap_validation_checks:
      - calico-etcd.kube-system.svc.cluster.local
      - google.com
      - kubernetes-etcd.kube-system.svc.cluster.local
      - kubernetes.default.svc.cluster.local
    upstream_servers:
      - 8.8.8.8
      - 8.8.4.4

  kubernetes:
    pod_cidr: 10.97.0.0/16
    service_cidr: 10.96.0.0/16
    service_ip: 10.96.0.1

  etcd:
    service_ip: 10.96.0.2
---
schema: promenade/Docker/v1
metadata:
  schema: metadata/Document/v1
  name: docker
  layeringDefinition:
    abstract: false
    layer: site
data:
  config:
    insecure-registries:
      - 10.24.20.19:30092
    live-restore: true
    storage-driver: overlay2
---
schema: promenade/HostSystem/v1
metadata:
  schema: metadata/Document/v1
  name: host-system
  layeringDefinition:
    abstract: false
    layer: site
data:
  files:
    - path: /opt/kubernetes/bin/kubelet
      tar_url: ${KUBELET_URL}
      tar_path: kubernetes/node/bin/kubelet
      mode: 0555
  images:
    coredns: ${IMAGE_COREDNS}
    helm:
      helm: ${IMAGE_HELM}
    kubernetes:
      kubectl: ${IMAGE_HYPERKUBE}
  packages:
    repositories:
      - deb http://apt.dockerproject.org/repo ubuntu-xenial main
    keys:
      - |-
        -----BEGIN PGP PUBLIC KEY BLOCK-----

        mQINBFWln24BEADrBl5p99uKh8+rpvqJ48u4eTtjeXAWbslJotmC/CakbNSqOb9o
        ddfzRvGVeJVERt/Q/mlvEqgnyTQy+e6oEYN2Y2kqXceUhXagThnqCoxcEJ3+KM4R
        mYdoe/BJ/J/6rHOjq7Omk24z2qB3RU1uAv57iY5VGw5p45uZB4C4pNNsBJXoCvPn
        TGAs/7IrekFZDDgVraPx/hdiwopQ8NltSfZCyu/jPpWFK28TR8yfVlzYFwibj5WK
        dHM7ZTqlA1tHIG+agyPf3Rae0jPMsHR6q+arXVwMccyOi+ULU0z8mHUJ3iEMIrpT
        X+80KaN/ZjibfsBOCjcfiJSB/acn4nxQQgNZigna32velafhQivsNREFeJpzENiG
        HOoyC6qVeOgKrRiKxzymj0FIMLru/iFF5pSWcBQB7PYlt8J0G80lAcPr6VCiN+4c
        NKv03SdvA69dCOj79PuO9IIvQsJXsSq96HB+TeEmmL+xSdpGtGdCJHHM1fDeCqkZ
        hT+RtBGQL2SEdWjxbF43oQopocT8cHvyX6Zaltn0svoGs+wX3Z/H6/8P5anog43U
        65c0A+64Jj00rNDr8j31izhtQMRo892kGeQAaaxg4Pz6HnS7hRC+cOMHUU4HA7iM
        zHrouAdYeTZeZEQOA7SxtCME9ZnGwe2grxPXh/U/80WJGkzLFNcTKdv+rwARAQAB
        tDdEb2NrZXIgUmVsZWFzZSBUb29sIChyZWxlYXNlZG9ja2VyKSA8ZG9ja2VyQGRv
        Y2tlci5jb20+iQI4BBMBAgAiBQJVpZ9uAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIe
        AQIXgAAKCRD3YiFXLFJgnbRfEAC9Uai7Rv20QIDlDogRzd+Vebg4ahyoUdj0CH+n
        Ak40RIoq6G26u1e+sdgjpCa8jF6vrx+smpgd1HeJdmpahUX0XN3X9f9qU9oj9A4I
        1WDalRWJh+tP5WNv2ySy6AwcP9QnjuBMRTnTK27pk1sEMg9oJHK5p+ts8hlSC4Sl
        uyMKH5NMVy9c+A9yqq9NF6M6d6/ehKfBFFLG9BX+XLBATvf1ZemGVHQusCQebTGv
        0C0V9yqtdPdRWVIEhHxyNHATaVYOafTj/EF0lDxLl6zDT6trRV5n9F1VCEh4Aal8
        L5MxVPcIZVO7NHT2EkQgn8CvWjV3oKl2GopZF8V4XdJRl90U/WDv/6cmfI08GkzD
        YBHhS8ULWRFwGKobsSTyIvnbk4NtKdnTGyTJCQ8+6i52s+C54PiNgfj2ieNn6oOR
        7d+bNCcG1CdOYY+ZXVOcsjl73UYvtJrO0Rl/NpYERkZ5d/tzw4jZ6FCXgggA/Zxc
        jk6Y1ZvIm8Mt8wLRFH9Nww+FVsCtaCXJLP8DlJLASMD9rl5QS9Ku3u7ZNrr5HWXP
        HXITX660jglyshch6CWeiUATqjIAzkEQom/kEnOrvJAtkypRJ59vYQOedZ1sFVEL
        MXg2UCkD/FwojfnVtjzYaTCeGwFQeqzHmM241iuOmBYPeyTY5veF49aBJA1gEJOQ
        TvBR8Q==
        =Fm3p
        -----END PGP PUBLIC KEY BLOCK-----
    additional:
      - ceph-common=10.2.9-0ubuntu0.16.04.1
    required:
      docker: docker-engine=1.13.1-0~ubuntu-xenial
      socat: socat=1.7.3.1-1
---
schema: promenade/Kubelet/v1
metadata:
  schema: metadata/Document/v1
  name: kubelet
  layeringDefinition:
    abstract: false
    layer: site
data:
  arguments:
    - --cni-bin-dir=/opt/cni/bin
    - --cni-conf-dir=/etc/cni/net.d
    - --eviction-max-pod-grace-period=-1
    - --network-plugin=cni
    - --node-status-update-frequency=5s
    - --v=5
  images:
    pause: gcr.io/google_containers/pause-amd64:3.0
---
schema: promenade/PKICatalog/v1
metadata:
  schema: metadata/Document/v1
  name: cluster-certificates
  layeringDefinition:
    abstract: false
    layer: site
data:
  certificate_authorities:
    kubernetes:
      description: CA for Kubernetes components
      certificates:
        - document_name: apiserver
          description: Service certificate for Kubernetes apiserver
          common_name: apiserver
          hosts:
            - localhost
            - 127.0.0.1
            - 10.96.0.1
            - apiserver.kubernetes.promenade
          kubernetes_service_names:
            - kubernetes.default.svc.cluster.local
        - document_name: kubelet-genesis
          common_name: system:node:n0
          hosts:
            - ${GENESIS_HOSTNAME}
            - ${GENESIS_IP}
          groups:
            - system:nodes
        - document_name: kubelet-n0
          common_name: system:node:n0
          hosts:
            - ${GENESIS_HOSTNAME}
            - ${GENESIS_IP}
          groups:
            - system:nodes
        - document_name: kubelet-n1
          common_name: system:node:n1
          hosts:
            - ${MASTER1_HOSTNAME}
            - ${MASTER1_IP}
          groups:
            - system:nodes
        - document_name: kubelet-n2
          common_name: system:node:n2
          hosts:
            - ${MASTER2_HOSTNAME}
            - ${MASTER2_IP}
          groups:
            - system:nodes
        - document_name: kubelet-n3
          common_name: system:node:n3
          hosts:
            - ${WORKER_HOSTNAME}
            - ${WORKER_IP}
          groups:
            - system:nodes
        - document_name: scheduler
          description: Service certificate for Kubernetes scheduler
          common_name: system:kube-scheduler
        - document_name: controller-manager
          description: certificate for controller-manager
          common_name: system:kube-controller-manager
        - document_name: proxy
          common_name: system:kube-proxy
        - document_name: admin
          common_name: admin
          groups:
            - system:masters
        - document_name: armada
          common_name: armada
          groups:
            - system:masters
        - document_name: coredns
          common_name: coredns
    kubernetes-etcd:
      description: Certificates for Kubernetes's etcd servers
      certificates:
        - document_name: apiserver-etcd
          description: etcd client certificate for use by Kubernetes apiserver
          common_name: apiserver
          # NOTE(mark-burnett): hosts not required for client certificates
        - document_name: kubernetes-etcd-anchor
          description: anchor
          common_name: anchor
        - document_name: kubernetes-etcd-genesis
          common_name: kubernetes-etcd-genesis
          hosts:
            - ${GENESIS_HOSTNAME}
            - ${GENESIS_IP}
            - 127.0.0.1
            - localhost
            - etcd.kubernetes.promenade
            - 10.96.0.2
        - document_name: kubernetes-etcd-n0
          common_name: kubernetes-etcd-n0
          hosts:
            - ${GENESIS_HOSTNAME}
            - ${GENESIS_IP}
            - 127.0.0.1
            - localhost
            - etcd.kubernetes.promenade
            - 10.96.0.2
        - document_name: kubernetes-etcd-n1
          common_name: kubernetes-etcd-n1
          hosts:
            - ${MASTER1_HOSTNAME}
            - ${MASTER1_IP}
            - 127.0.0.1
            - localhost
            - etcd.kubernetes.promenade
            - 10.96.0.2
        - document_name: kubernetes-etcd-n2
          common_name: kubernetes-etcd-n2
          hosts:
            - ${MASTER2_HOSTNAME}
            - ${MASTER2_IP}
            - 127.0.0.1
            - localhost
            - etcd.kubernetes.promenade
            - 10.96.0.2
        - document_name: kubernetes-etcd-n3
          common_name: kubernetes-etcd-n3
          hosts:
            - ${WORKER_HOSTNAME}
            - ${WORKER_IP}
            - 127.0.0.1
            - localhost
            - etcd.kubernetes.promenade
            - 10.96.0.2
    kubernetes-etcd-peer:
      certificates:
        - document_name: kubernetes-etcd-genesis-peer
          common_name: kubernetes-etcd-genesis-peer
          hosts:
            - ${GENESIS_HOSTNAME}
            - ${GENESIS_IP}
            - 127.0.0.1
            - localhost
            - etcd.kubernetes.promenade
            - 10.96.0.2
        - document_name: kubernetes-etcd-n0-peer
          common_name: kubernetes-etcd-n0-peer
          hosts:
            - ${GENESIS_HOSTNAME}
            - ${GENESIS_IP}
            - 127.0.0.1
            - localhost
            - etcd.kubernetes.promenade
            - 10.96.0.2
        - document_name: kubernetes-etcd-n1-peer
          common_name: kubernetes-etcd-n1-peer
          hosts:
            - ${MASTER1_HOSTNAME}
            - ${MASTER1_IP}
            - 127.0.0.1
            - localhost
            - etcd.kubernetes.promenade
            - 10.96.0.2
        - document_name: kubernetes-etcd-n2-peer
          common_name: kubernetes-etcd-n2-peer
          hosts:
            - ${MASTER2_HOSTNAME}
            - ${MASTER2_IP}
            - 127.0.0.1
            - localhost
            - etcd.kubernetes.promenade
            - 10.96.0.2
        - document_name: kubernetes-etcd-n3-peer
          common_name: kubernetes-etcd-n3-peer
          hosts:
            - ${WORKER_HOSTNAME}
            - ${WORKER_IP}
            - 127.0.0.1
            - localhost
            - etcd.kubernetes.promenade
            - 10.96.0.2
    calico-etcd:
      description: Certificates for Calico etcd client traffic
      certificates:
        - document_name: calico-etcd-anchor
          description: anchor
          common_name: anchor
        - document_name: calico-etcd-${GENESIS_HOSTNAME}
          common_name: calico-etcd-${GENESIS_HOSTNAME}
          hosts:
            - ${GENESIS_HOSTNAME}
            - ${GENESIS_IP}
            - 127.0.0.1
            - localhost
            - etcd.calico.promenade
            - 10.96.232.136
        - document_name: calico-etcd-${MASTER1_HOSTNAME}
          common_name: calico-etcd-${MASTER1_HOSTNAME}
          hosts:
            - ${MASTER1_HOSTNAME}
            - ${MASTER1_IP}
            - 127.0.0.1
            - localhost
            - etcd.calico.promenade
            - 10.96.232.136
        - document_name: calico-etcd-${MASTER2_HOSTNAME}
          common_name: calico-etcd-${MASTER2_HOSTNAME}
          hosts:
            - ${MASTER2_HOSTNAME}
            - ${MASTER2_IP}
            - 127.0.0.1
            - localhost
            - etcd.calico.promenade
            - 10.96.232.136
        - document_name: calico-etcd-${WORKER_HOSTNAME}
          common_name: calico-etcd-${WORKER_HOSTNAME}
          hosts:
            - ${WORKER_HOSTNAME}
            - ${WORKER_IP}
            - 127.0.0.1
            - localhost
            - etcd.calico.promenade
            - 10.96.232.136
        - document_name: calico-node
          common_name: calcico-node
    calico-etcd-peer:
      description: Certificates for Calico etcd clients
      certificates:
        - document_name: calico-etcd-${GENESIS_HOSTNAME}-peer
          common_name: calico-etcd-${GENESIS_HOSTNAME}-peer
          hosts:
            - ${GENESIS_HOSTNAME}
            - ${GENESIS_IP}
            - etcd.calico.promenade
            - 10.96.232.136
        - document_name: calico-etcd-${WORKER_HOSTNAME}
          common_name: calico-etcd-${WORKER_HOSTNAME}
          hosts:
            - ${WORKER_HOSTNAME}
            - ${WORKER_IP}
            - 127.0.0.1
            - localhost
            - etcd.calico.promenade
            - 10.96.232.136
        - document_name: calico-node
          common_name: calcico-node
    calico-etcd-peer:
      description: Certificates for Calico etcd clients
      certificates:
        - document_name: calico-etcd-${GENESIS_HOSTNAME}-peer
          common_name: calico-etcd-${GENESIS_HOSTNAME}-peer
          hosts:
            - ${GENESIS_HOSTNAME}
            - ${GENESIS_IP}
            - 127.0.0.1
            - localhost
            - etcd.calico.promenade
            - 10.96.232.136
        - document_name: calico-etcd-${MASTER1_HOSTNAME}-peer
          common_name: calico-etcd-${MASTER1_HOSTNAME}-peer
          hosts:
            - ${MASTER1_HOSTNAME}
            - ${MASTER1_IP}
            - 127.0.0.1
            - localhost
            - etcd.calico.promenade
            - 10.96.232.136
        - document_name: calico-etcd-${MASTER2_HOSTNAME}-peer
          common_name: calico-etcd-${MASTER1_HOSTNAME}-peer
          hosts:
            - ${MASTER2_HOSTNAME}
            - ${MASTER2_IP}
            - 127.0.0.1
            - localhost
            - etcd.calico.promenade
            - 10.96.232.136
        - document_name: calico-etcd-${WORKER_HOSTNAME}-peer
          common_name: calico-etcd-${WORKER_HOSTNAME}-peer
          hosts:
            - ${WORKER_HOSTNAME}
            - ${WORKER_IP}
            - 127.0.0.1
            - localhost
            - etcd.calico.promenade
            - 10.96.232.136
        - document_name: calico-node-peer
          common_name: calcico-node-peer
  keypairs:
    - name: service-account
      description: Service account signing key for use by Kubernetes controller-manager.
...
