---
# TODO: Version kubelet, with checksum
- name: Download and install the kubelet binary
  get_url:
    url: "http://storage.googleapis.com/kubernetes-release/release/{{ kubelet_version }}/bin/linux/amd64/kubelet"
    dest: /usr/local/bin/kubelet
#    checksum: md5:33af080e876b1f3d481b0ff1ceec3ab8
    mode: 0755

# Service for a master kubelet
- name: Load and start/restart the kubelet.service for the master
  when: inventory_hostname in groups['master']
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
  notify: restart kubelet

# Service for a worker kubelet
- name: Load and start/restart the kubelet.service for the workers
  when: inventory_hostname in groups['workers']
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service
  notify: restart kubelet

- name: Enable the kubelet.service to be started on boot
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon_reload: yes
